### ISSUE TITLE
peer-to-peer code review

### ISSUE THREAD

**Issue by thecodechaser** [Mithi-code/webpack-todo#6]
feedbacks, suggestions, improvements.

**Comment by thecodechaser** [comment]
## Hello, @Mithi-code   👋 

You did great so far, Your project is already looking great, You probably did hard work for this 👍. 
![greetings-handshake](https://user-images.githubusercontent.com/83803414/144983724-14efa4a6-e719-401d-91c8-f679000acf36.gif)


I have some suggestions for you, you can look into these changes 😄.

### Suggested Changes ♻️ 

- [x] You can update your dist/ directory.
      Your live version in the readme file is not working, I think you can update your dist/ directory using `npm run build` and commit the changes.

Great job 👍

**Comment by Gbengacode** [comment]
Weldone Mithi-code,
Great job but it have the following observation
 elems.forEach((v) => {
    v.addEventListener('change', () => {
      v.parentNode.classList.toggle('checked');
      todoList[v.parentElement.parentElement.id.split('-')[1]].done = v.checked;
      localStorage.setItem('todoList', JSON.stringify(todoList));
    });
  });
}
document.querySelector('.rmBtn').addEventListener('click', () => {
  todoList = todoList.filter((x) => !x.done);
  localStorage.setItem('todoList', JSON.stringify(todoList));
  render();
});
it will be nice if you give a more meaningful iterated to-do list name.
something like this
`todoList = todoList.filter((item) => !item.done)`

**Comment by vic778** [comment]
HI @thecodechaser 
 - your code looks perfect nothing to say 
  
 cheers... happy coding

**Comment by Mithi-code** [comment]
Thanks mate for review 

closing #6
